# Site settings
title: "Currículo de Juliana Tosta Filhote Goulart"
description: "Currículo Vitae de Juliana T F Goulart."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Juliana Tosta Filhote Goulart "
resume_title:                   "Especialista em Gestão Pública Municipal"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "juliana.goulart@rio.rj.gov.br"
resume_contact_email_academic:  "jufilhote@id.uff.br"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(21) 99133-2292"
resume_contact_address:         "Rua Ibituruna, 38 Apto. 302 - Maracanã, Rio de Janeiro"

resume_header_contact_info:     "Rua Ibituruna, 38 Apto. 302 - Maracanã, Rio de Janeiro • (21) 99133-2292 • juliana.goulart@rio.rj.gov.br"
display_header_contact_info:    "false"

resume_header_intro: "<p>Especialista em Gestão Pública Municipal pela Universidade Federal Fluminense, bacharel em Turismo pela Universidade Veiga de Almeida, servidora pública municipal concursada da Prefeitura da Cidade do Rio de Janeiro desde junho de 2016. Primeiramente, ocupei o cargo de Assistente de Ouvidoria na Ouvidoria da Secretaria Municipal de Transportes. Atualmente, exerço o cargo de Assistente em Transparência Ativa, da Coordenadoria Técnica de Acesso à Informação, da Subsecretaria de Integração Governamental e Transparência, da Secretaria Municipal da Casa Civil.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/julianatfg/"
  resume_twitter_url:           "http://twitter.com/juleees"
  # resume_telegram_url:          "https://t.me/jugoul"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "http://instagram.com/sublondon"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  #resume_whatsapp_url:          "https://wa.me/5521991332292"
  #resume_telegram_url:          "https://t.me/jugoul"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
